/**
 * @file generate_t_table.cpp
 * @brief Generate a dense T(q,p) inductance shape-factor lookup table.
 * @author Winston Meursault
 *
 * Computes T(q,p) via the reference Bessel/Struve kernel for every grid
 * point at dq=dp=0.002 resolution and writes the result as a constexpr
 * C++ header (include/coilgun/physics/lookup_table_data.hpp).
 *
 * Usage: ./generate_t_table [output_path]
 *   output_path defaults to include/coilgun/physics/lookup_table_data.hpp
 */

#include "coilgun/physics/self_inductance.hpp"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

using namespace std::chrono;

// ---------------------------------------------------------------------------
// table geometry
// ---------------------------------------------------------------------------
constexpr double k_q_min = 0.05;
constexpr double k_q_max = 4.00;
constexpr double k_p_min = 1.05;
constexpr double k_p_max = 4.00;
constexpr double k_dq    = 0.002;
constexpr double k_dp    = 0.002;

constexpr int k_nq = static_cast<int>((k_q_max - k_q_min) / k_dq + 0.5) + 1;
constexpr int k_np = static_cast<int>((k_p_max - k_p_min) / k_dp + 0.5) + 1;
constexpr int k_total = k_nq * k_np;

constexpr int k_report_interval = k_total / 1000;   // 0.1 % steps

// ---------------------------------------------------------------------------
// progress tracking
// ---------------------------------------------------------------------------
std::atomic<int> g_completed{0};
std::mutex        g_print_mutex;

void worker_thread(std::vector<double>& table, int thread_id, int n_threads) {
    const auto t_start = steady_clock::now();

    for (int idx = thread_id; idx < k_total; idx += n_threads) {
        const int iq = idx / k_np;
        const int ip = idx % k_np;
        const double q = k_q_min + iq * k_dq;
        const double p = k_p_min + ip * k_dp;

        table[idx] = coilgun::physics::inductance_shape_factor_reference(q, p);

        const int done = ++g_completed;

        if (done % k_report_interval == 0) {
            std::lock_guard<std::mutex> lk(g_print_mutex);
            const auto t_now = steady_clock::now();
            const double elapsed = duration<double>(t_now - t_start).count();
            const double frac    = static_cast<double>(done) / k_total;
            const double eta     = (frac > 0.0)
                ? elapsed / frac * (1.0 - frac) : 0.0;

            std::printf("[%6.1fs] %5.1f%% done | elapsed %5.0fs | ETA %5.0fs | "
                        "%d/%d\n",
                        elapsed, frac * 100.0, elapsed, eta, done, k_total);
            std::fflush(stdout);
        }
    }
}

// ---------------------------------------------------------------------------
// header writer
// ---------------------------------------------------------------------------
void write_header(const std::string& path, const std::vector<double>& table) {
    std::ofstream out(path);
    if (!out) {
        std::fprintf(stderr, "ERROR: cannot write %s\n", path.c_str());
        std::exit(1);
    }

    out << "/**\n"
           " * @file lookup_table_data.hpp\n"
           " * @brief Dense T(q,p) inductance shape-factor table (auto-generated).\n"
           " *\n"
           " * Grid: q \\in [" << k_q_min << ", " << k_q_max << "], "
              "p \\in [" << k_p_min << ", " << k_p_max << "]\n"
           " * Step: dq = " << k_dq << ", dp = " << k_dp << "\n"
           " * Entries: " << k_nq << " × " << k_np
           << " = " << k_total << "\n"
           " * Generated by tools/generate_t_table.cpp.\n"
           " * @author Winston Meursault\n"
           " */\n\n"
           "#pragma once\n\n"
           "#include <cstddef>\n\n"
           "namespace coilgun::physics::detail {\n\n"
           "constexpr int k_table_nq = " << k_nq << ";\n"
           "constexpr int k_table_np = " << k_np << ";\n"
           "constexpr double k_table_dq = " << k_dq << ";\n"
           "constexpr double k_table_dp = " << k_dp << ";\n"
           "constexpr double k_table_q0 = " << k_q_min << ";\n"
           "constexpr double k_table_p0 = " << k_p_min << ";\n"
           "constexpr double k_table_q_max = " << k_q_max << ";\n"
           "constexpr double k_table_p_max = " << k_p_max << ";\n\n"
           "constexpr double k_t_table_data[] = {\n";

    constexpr int k_per_line = 5;
    for (int idx = 0; idx < k_total; ++idx) {
        char buf[64];
        std::snprintf(buf, sizeof(buf), "%.15e", table[idx]);
        out << "    " << buf;
        if (idx < k_total - 1) out << ",";
        if ((idx + 1) % k_per_line == 0) out << "\n";
    }

    out << "\n};\n\n"
           "constexpr std::size_t k_t_table_size = " << k_total << ";\n\n"
           "} // namespace coilgun::physics::detail\n";
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char** argv) {
    std::string out_path = (argc >= 2)
        ? argv[1]
        : "include/coilgun/physics/lookup_table_data.hpp";

    const int n_threads = std::max(1u, std::thread::hardware_concurrency() - 4);
    std::printf("T(q,p) table generator\n"
                "  Grid: q[%.2f:%.2f:%.3f] × p[%.2f:%.2f:%.3f]\n"
                "  Size: %d × %d = %d entries\n"
                "  Threads: %d\n"
                "  Output: %s\n\n",
                k_q_min, k_q_max, k_dq, k_p_min, k_p_max, k_dp,
                k_nq, k_np, k_total, n_threads, out_path.c_str());

    std::vector<double> table(k_total, 0.0);

    const auto t0 = steady_clock::now();

    std::vector<std::thread> threads;
    threads.reserve(n_threads);
    for (int t = 0; t < n_threads; ++t) {
        threads.emplace_back(worker_thread, std::ref(table), t, n_threads);
    }
    for (auto& t : threads) t.join();

    const auto t1 = steady_clock::now();
    const double total_time = duration<double>(t1 - t0).count();

    std::printf("\nComputation: %.1f s\n"
                "Writing header...\n", total_time);

    write_header(out_path, table);

    std::printf("Done.  Table written to %s\n", out_path.c_str());
    return 0;
}
